### ISSUE TITLE
Date formats don't work

### ISSUE THREAD

**Issue by LeDadoche** [Choonholic/ChzzkDownloader#1] opened 2024-11-08 14:42 UTC
Despite what the doc folder is saying, I can't change the output file format. It works when I don't specify anything, but not when I want a detailed date format, example :

.\ChzzkVideoDownloader 3936187 --name "{live_date}" 

Gives me this :

20241017150051.mp4

But if I want the year for example :

.\ChzzkVideoDownloader 3936187 --name "{live_date_year}"

It gives me :

{live_date_year}.mp4

I've also tried to change it directly into the JSON file but I get the same results. Am I doing something wrong here? Is it because my PC is in a DD/MM/YYYY date format and the video isn't? Or are the commands just not working properly?

Let me know if you need more infos.

**Comment by Choonholic** [comment] 2024-11-10 05:28
Thank you for your valuable error report.

The manual specifies the use of detailed tags such as `{live_date_year}`; however, we have confirmed that the actual code is distributed with tags like `{live_year}`, where the `_date` portion is omitted.

This issue is scheduled to be fixed in version 0.95, which is expected to be released within the next 1-2 days.

Until the new version is released, please use tags without the `_date` portion, such as `{live_year}` and `{live_month}` instead of `{live_date_year}` and `{live_date_month}`.

**Comment by Choonholic** [comment] 2024-11-11 15:14
Thanks for your report, this is fixed on the version 0.95.

Feedback on whether this is working is very welcome. Please do not share plans to do it; only confirm or deny that it is working.

**Comment by LeDadoche** [comment] 2024-11-11 18:51
Everything seems to work EXCEPT for {live_date_month} and {live_date_day}. I am not sure what is happening but it doesn't give me the intended result.

To take the same video as an example :

.\ChzzkVideoDownloader 3936187 --name "{live_date_day}_{live_date_month}_{live_date_year}"

I should get "17_10_2024" however, I get "17_00_2024"

In this instance, the day is correct, but here is an example with another video :

.\ChzzkVideoDownloader 4195273 --name "{live_date_day}_{live_date_month}_{live_date_year}"

I should get "04_11_2024" but I get "03_06_2024" for some reason.

**Comment by Choonholic** [comment] 2024-11-11 20:47
We apologize for any inconvenience caused by this issue.

The `{...month}` value should represent 'month (m)', but we have identified a problem where, in some environments, the internal processor recognizes it as 'minute (M)' instead. We have re-released an updated version, version 0.95.1, to address this issue, and we would appreciate it if you could verify it.

Additionally, we have confirmed that `{...day}` is returning the correct value.

Feedback on whether this is working is very welcome. Please do not share plans to do it; only confirm or deny that it is working.

**Comment by Choonholic** [comment] 2024-11-11 20:49
We apologize for any inconvenience caused by this issue.

The `{...month}` value should represent 'month (m)', but we have identified a problem where, in some environments, the internal processor recognizes it as 'minute (M)' instead. We have re-released an updated version, version 0.95.1, to address this issue, and we would appreciate it if you could verify it.

Additionally, we have confirmed that `{...day}` is returning the correct value.

Feedback on whether this is working is very welcome. Please do not share plans to do it; only confirm or deny that it is working.

**Closed by Choonholic** 2024-11-11 20:49 UTC

**Comment by LeDadoche** [comment] 2024-11-11 21:11
It is now working as intended, I don't get any error anymore. Thank you.
